services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    image: egress-ips-app:latest
    container_name: egress-ips-app
    env_file: .env

    # Run your main script
    command: ["python", "src/webapp/app.py"]
    
    ports:
      - "5000:5000"

    # Mount source files and logs
    volumes:
      - ./src:/app/src
      - ./src/logs:/app/src/logs